name = "Marcel Arie"
downloads-dir = "~/downloads"
signature = """
--
Regards, Marcel
"""

[marcelarie]
default = true
email = "info@marcelarie.com"

imap-host = "imap.marcelarie.com"
imap-port = 993
imap-login = "info@marcelarie.com"
imap-passwd-cmd = "pass show info-marcelarie"

smtp-host = "smtp.marcelarie.com"
smtp-port = 465
smtp-login = "info@marcelarie.com"
smtp-passwd-cmd = "security find-internet-password -gs marcelarie -w"

[googlillo]
email = "googlillo@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "googlillo@gmail.com"
imap-passwd-cmd = "pass show info-marcelarie"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "googlillo@gmail.com"
smtp-passwd-cmd = "security find-internet-password -gs gmail -w"
