edition = "2021"
empty_item_single_line = false
format_code_in_doc_comments = true
match_arm_leading_pipes = "Preserve"
max_width = 80
struct_field_align_threshold = 20
use_field_init_shorthand = true
