tap "1password/tap"
tap "charmbracelet/tap"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "koekeishiya/formulae"
tap "ms-jpq/sad"
tap "wez/wezterm"
brew "webp"
brew "pkg-config"
brew "cmake"
brew "cowsay"
brew "direnv"
brew "exa"
brew "fd"
brew "openssl@1.1"
brew "fish"
brew "fzf"
brew "gcc"
brew "geos"
brew "git"
brew "libgcrypt"
brew "gnupg"
brew "gsl"
brew "imagemagick@6", link: true
brew "node"
brew "jsonlint"
brew "libgphoto2"
brew "libxml2"
brew "sqlite"
brew "llvm"
brew "markdownlint-cli"
brew "mas"
brew "mysql@5.7", link: true
brew "nushell"
brew "nvm"
brew "percona-toolkit"
brew "postgresql@12"
brew "python@3.10", link: false
brew "python@3.9"
brew "qpdf"
brew "rbenv"
brew "ripgrep"
brew "starship"
brew "stylua"
brew "topgrade"
brew "urlview"
brew "yarn"
brew "zoxide"
brew "charmbracelet/tap/vhs"
brew "jakehilborn/jakehilborn/displayplacer"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "ms-jpq/sad/sad"
cask "chromium"
cask "font-fira-code-nerd-font"
cask "launchcontrol"
cask "neovide"
cask "qutebrowser"
cask "stretchly"
cask "wezterm-nightly"
cask "whichspace"
mas "Flow", id: 1423210932
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
