tap "1password/tap"
tap "charmbracelet/tap"
tap "dustinblackman/tap"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "jkfran/killport"
tap "koekeishiya/formulae"
tap "marcelmanzanares2/local-tap"
tap "ms-jpq/sad"
tap "wez/wezterm"
brew "webp"
brew "jpeg-xl"
brew "coreutils"
brew "asdf"
brew "atuin"
brew "bottom"
brew "gcc"
brew "btop"
brew "pkg-config"
brew "cmake"
brew "cowsay"
brew "openssl@1.1"
brew "curl"
brew "difftastic"
brew "direnv"
brew "exa"
brew "fd"
brew "fend"
brew "fish"
brew "fnm"
brew "fzf"
brew "geos"
brew "ghc"
brew "ghcup"
brew "git"
brew "gitoxide"
brew "libgcrypt"
brew "gnupg"
brew "gsl"
brew "imagemagick@6", link: true
brew "node"
brew "jsonlint"
brew "libgphoto2"
brew "libxml2"
brew "sqlite"
brew "llvm"
brew "llvm@11"
brew "luarocks"
brew "markdownlint-cli"
brew "marksman"
brew "mas"
brew "micro"
brew "mycli"
brew "mysql@5.7", link: true
brew "neovim"
brew "nnn"
brew "nushell"
brew "nvm"
brew "parallel"
brew "percona-toolkit"
brew "pipx"
brew "postgresql@12"
brew "postgresql@14", restart_service: true
brew "pspg"
brew "python@3.10"
brew "python@3.9"
brew "qemu"
brew "qpdf"
brew "rbenv"
brew "ripgrep"
brew "ruff"
brew "sd"
brew "spark"
brew "starship"
brew "stylua"
brew "tmuxinator"
brew "topgrade"
brew "treefmt"
brew "urlview"
brew "yarn"
brew "zellij"
brew "zoxide"
brew "charmbracelet/tap/vhs"
brew "dustinblackman/tap/languagetool-code-comments"
brew "jakehilborn/jakehilborn/displayplacer"
brew "jkfran/killport/killport"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "marcelmanzanares2/local-tap/git@2.25.1", link: false
brew "ms-jpq/sad/sad"
cask "chromium"
cask "docker"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "launchcontrol"
cask "macvim"
cask "neovide"
cask "qutebrowser"
cask "stretchly"
cask "utm"
cask "vscodium"
cask "wezterm-nightly"
cask "whichspace"
mas "Amphetamine", id: 937984704
mas "Flow", id: 1423210932
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Little Snitch Mini", id: 1629008763
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WhatsApp", id: 1147396723
