complete -c coco -n "__fish_use_subcommand" -s B -l breaking-change -d 'BREAKING CHANGE commit'
complete -c coco -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c coco -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c coco -n "__fish_use_subcommand" -f -a "generate-completions" -d 'Generate shell completions'
complete -c coco -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c coco -n "__fish_seen_subcommand_from generate-completions" -s h -l help -d 'Prints help information'
complete -c coco -n "__fish_seen_subcommand_from generate-completions" -s V -l version -d 'Prints version information'
complete -c coco -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c coco -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
