complete -c cog -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_use_subcommand" -f -a "verify" -d 'Verify a single commit message'
complete -c cog -n "__fish_use_subcommand" -f -a "init" -d 'Install cog config files'
complete -c cog -n "__fish_use_subcommand" -f -a "check" -d 'Verify all commit message against the conventional commit specification'
complete -c cog -n "__fish_use_subcommand" -f -a "edit" -d 'Interactively rename invalid commit message'
complete -c cog -n "__fish_use_subcommand" -f -a "log" -d 'Like git log but for conventional commits'
complete -c cog -n "__fish_use_subcommand" -f -a "changelog" -d 'Display a changelog for a given commit oid range'
complete -c cog -n "__fish_use_subcommand" -f -a "bump" -d 'Commit changelog from latest tag to HEAD and create a new tag'
complete -c cog -n "__fish_use_subcommand" -f -a "install-hook" -d 'Add git hooks to the repository'
complete -c cog -n "__fish_use_subcommand" -f -a "generate-completions" -d 'Generate shell completions'
complete -c cog -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cog -n "__fish_seen_subcommand_from verify" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from verify" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from check" -s l -l from-latest-tag -d 'Check commit history, starting from the latest tag to HEAD'
complete -c cog -n "__fish_seen_subcommand_from check" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from check" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from log" -s t -l type -d 'filter on commit type'
complete -c cog -n "__fish_seen_subcommand_from log" -s a -l author -d 'filter on commit author'
complete -c cog -n "__fish_seen_subcommand_from log" -s s -l scope -d 'filter on commit scope'
complete -c cog -n "__fish_seen_subcommand_from log" -s B -l breaking-change -d 'filter BREAKING CHANGE commit'
complete -c cog -n "__fish_seen_subcommand_from log" -s e -l no-error -d 'omit error on the commit log'
complete -c cog -n "__fish_seen_subcommand_from log" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from log" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from changelog" -s f -l from -d 'Generate the changelog from this commit or tag ref, default latest tag'
complete -c cog -n "__fish_seen_subcommand_from changelog" -s t -l to -d 'Generate the changelog to this commit or tag ref, default HEAD'
complete -c cog -n "__fish_seen_subcommand_from changelog" -s a -l at -d 'Generate the changelog for a specific git tag'
complete -c cog -n "__fish_seen_subcommand_from changelog" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from changelog" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from bump" -s v -l version -d 'Manually set the next version'
complete -c cog -n "__fish_seen_subcommand_from bump" -l pre -d 'Set the pre-release version'
complete -c cog -n "__fish_seen_subcommand_from bump" -s c -l config -d 'Specify path to hooks config file'
complete -c cog -n "__fish_seen_subcommand_from bump" -s a -l auto -d 'Atomatically suggest the next version'
complete -c cog -n "__fish_seen_subcommand_from bump" -s M -l major -d 'Increment the major version'
complete -c cog -n "__fish_seen_subcommand_from bump" -s p -l patch -d 'Increment the patch version'
complete -c cog -n "__fish_seen_subcommand_from bump" -s m -l minor -d 'Increment the minor version'
complete -c cog -n "__fish_seen_subcommand_from bump" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from install-hook" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from install-hook" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from generate-completions" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from generate-completions" -s V -l version -d 'Prints version information'
complete -c cog -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cog -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
