#!/usr/bin/env bash
#
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: rofi and a web browser
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor, Ali Furkan Yıldız

# Defining our web browser.
DMBROWSER="brave"

# An array of search engines.  You can edit this list to add/remove
# search engines. The format must be: "engine_name - url".
# The url format must allow for the search keywords at the end of the url.
# For example: https://www.amazon.com/s?k=XXXX searches Amazon for 'XXXX'.
declare -a options=(
"amazon - https://www.amazon.es/s?k="
"archaur - https://aur.archlinux.org/packages/?O=0&K="
"archpkg - https://archlinux.org/packages/?sort=&q="
"archwiki - https://wiki.archlinux.org/index.php?search="
"cliki - https://www.cliki.net/site/search?query="
"coinbase - https://www.coinbase.com/price?query="
"duckduckgo - https://duckduckgo.com/?q="
"github - https://github.com/search?q="
"gitlab - https://gitlab.com/search?search="
"google - https://www.google.com/search?q="
"googleimages - https://www.google.com/search?hl=en&tbm=isch&q="
"reddit - https://www.reddit.com/search/?q="
"rust book - https://doc.rust-lang.org/book/?search="
"rust docs - https://doc.rust-lang.org/beta/std/index.html?search="
"crates.io - https://crates.io/search?q="
"stackoverflow - https://stackoverflow.com/search?q="
"google translate - https://translate.google.com/?sl=auto&tl=en&text="
"urban dic - https://www.urbandictionary.com/define.php?term="
"webster - https://www.merriam-webster.com/dictionary/"
"wikipedia - https://en.wikipedia.org/wiki/"
"wiktionary - https://en.wiktionary.org/wiki/"
"youtube - https://www.youtube.com/results?search_query="
)

# Picking a search engine.
while [ -z "$engine" ]; do
enginelist=$(printf '%s\n' "${options[@]}" | rofi -dmenu -theme minimal -font "Fira Code 10" -i -l 20 -p 'search engines  ') || exit
engineurl=$(echo "$enginelist" | awk '{print $NF}')
engine=$(echo "$enginelist" | awk '{print $1}')
done

# Searching the chosen engine.
while [ -z "$query" ]; do
query=$(echo "$engine" | rofi -dmenu -theme minimal -font "Fira Code 10" -p 'search query  ') || exit
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query"

