[greenclip]
  history_file = "/home/marcel/.cache/greenclip.history"
  max_history_length = 1000
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  use_primary_selection_as_input = true
  blacklisted_applications = []
  enable_image_support = true
  image_cache_directory = "/tmp/greenclip"
  static_history = [
      '(╯°□°）╯',
      '¯\_(ツ)_/¯',
      "my $d = driver('",
      "$d->category_products('",
      "$d->get_product('",
      "$d->fetch_product('",
      "my $cp = $d->category_products('",
      'my $res = Mojo::Collection->new( @$cp )->map(sub { $d->fetch_product($_) })',
      'my $cp = Mojo::Collection->new($d->categories_with_products)->map(sub{ say "#############".$_->{id}."#############"; $d->category_products($_->{id}) })->flatten;',
      'my $fp = $cp->map(sub { $d->fetch_product($_) })->compact->flatten;',
      "ñ",
]
