#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "Usage: zk-new <title>"
    exit 1
fi

if not command -v zk >/dev/null 2>&1; then
    echo "Error: 'zk' command not found."
    exit 1
fi

zk new --title "$@"
